name: Fetch social feeds

on:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i node-fetch@3 --save-dev
      - name: Run fetch script
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: node .github/scripts/fetch-social.mjs
      - name: Commit updated feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/social_feeds.json || true
          git commit -m "chore: update social feeds" || echo "No changes"
          git push

