name: Generate WebP assets

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-webp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install converter deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i sharp@^0.33.3 --silent

      - name: Convert images to WebP
        run: node .github/scripts/convert-webp.mjs

      - name: Commit WebP files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images/**/*.webp images/*.webp || true
          git commit -m "chore: generate webp assets" || echo "No changes"
          git push || echo "Nothing to push"

